{
  pkgs,
  userName,
  ...
}:
{
  home.username = userName;
  home.homeDirectory = "/Users/${userName}";

  home.packages = with pkgs; [
    fd
    hello
  ];

  programs.git = {
    enable = true;
    settings.init.defaultBranch = "main";
  };

  home.sessionVariables = {
    EDITOR = "vim";
  };

  xdg.configFile."nix-playground/example.conf".text = ''
    # Generated by the evaluation-only macOS example.
    greeting = "hello"
  '';

  # Compatibility version, not the Home Manager package version.
  home.stateVersion = "26.11";
}
